name: Build and Push Docker Image

on:
  push:
    branches: [test]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Create backend .env
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
          PASSWORD_SALT: ${{ secrets.PASSWORD_SALT }}
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
        run: |
          cat <<EOF > backend/.env
          MONGO_URI=$MONGO_URI
          JWT_SECRET=$JWT_SECRET
          REDIS_HOST=$REDIS_HOST
          REDIS_PORT=$REDIS_PORT
          OPENAI_API_KEY=$OPENAI_API_KEY
          ENCRYPTION_KEY=$ENCRYPTION_KEY
          PASSWORD_SALT=$PASSWORD_SALT
          NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
          EOF

      - name: Create frontend .env.local
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_SOCKET_URL : ${{ secrets.NEXT_PUBLIC_SOCKET_URL }}
          NEXT_PUBLIC_ENCRYPTION_KEY: ${{ secrets.NEXT_PUBLIC_ENCRYPTION_KEY }}
          NEXT_PUBLIC_PASSWORD_SALT: ${{ secrets.NEXT_PUBLIC_PASSWORD_SALT }}
        run: |
          cat <<EOF > frontend/.env.local
          NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
          NEXT_PUBLIC_SOCKET_URL=$NEXT_PUBLIC_SOCKET_URL
          NEXT_PUBLIC_ENCRYPTION_KEY=$NEXT_PUBLIC_ENCRYPTION_KEY
          NEXT_PUBLIC_PASSWORD_SALT=$NEXT_PUBLIC_PASSWORD_SALT
          
          EOF

      - name: Create chat-server .env
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
          PASSWORD_SALT: ${{ secrets.PASSWORD_SALT }}
        run: |
          cat <<EOF > chat-server/.env
          MONGO_URI=$MONGO_URI
          JWT_SECRET=$JWT_SECRET
          REDIS_HOST=$REDIS_HOST
          REDIS_PORT=$REDIS_PORT
          OPENAI_API_KEY=$OPENAI_API_KEY
          ENCRYPTION_KEY=$ENCRYPTION_KEY
          PASSWORD_SALT=$PASSWORD_SALT
          PORT=4000
          EOF

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t gmltn9233/ktb13-chat:latest .

      - name: Push Docker image
        run: |
          docker push gmltn9233/ktb13-chat:latest