name: Build & Upload Frontend to S3 (Static + SSR)

on:
  push:
    branches: [main]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      working-directory: frontend
      run: npm install

    - name: Build frontend
      working-directory: frontend
      run: npm run build

    # 정적 파일 S3로 업로드 (CDN 용)
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Upload static files to S3 (for CDN)
      run: |
        aws s3 sync frontend/.next/static s3://ktb13-static/static --delete
        aws s3 sync frontend/public s3://ktb13-static/public --delete

    # SSR 용 전체 빌드 zip
    - name: Prepare SSR bundle
      run: |
        mkdir ssr-dist
        cp -r frontend/.next ssr-dist/.next
        cp -r frontend/node_modules ssr-dist/node_modules || echo "node_modules missing (optional)"
        cp frontend/next.config.js ssr-dist/
        cp frontend/package.json ssr-dist/
        cp frontend/package-lock.json ssr-dist/ || true
        cd ssr-dist && zip -r frontend-ssr.zip .

    - name: Upload SSR bundle to S3
      run: |
        aws s3 cp ssr-dist/frontend-ssr.zip s3://ktb13-bundle/frontend-ssr.zip
