name: Build & Upload Frontend & Backend to S3

on:
  push:
    branches: [main]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Install frontend dependencies
        run: npm install --prefix frontend --legacy-peer-deps

      - name: Build frontend for SSR
        run: npm run build --prefix frontend

      - name: Upload frontend static files to S3
        run: aws s3 sync frontend/.next/static s3://ktb13-bucket/static/

      - name: Upload frontend SSR files to S3
        run: aws s3 cp frontend/.next/server s3://ktb13-bucket/frontend/ --recursive

      - name: Upload backend source files to S3
        run: |
          aws s3 cp backend/ s3://ktb13-bucket/backend/ --recursive \
            --exclude "node_modules/*"
